[package]
name = "bevy_toolbar"
version = "0.1.3"
edition = "2021"

[dependencies]
bevy_egui = "0.10"
strum = "0.23.0"
strum_macros = "0.23.1"

[dependencies.bevy]
version = "0.6"
default-features = false
